### PR TITLE
Added support for packit

### PR DESCRIPTION
**Pull request by jirihnidek**
* Added `.packit.yaml` file
* Changed spec file a little bit

### CODE REVIEW

**Comment by TomasTomecek** [comment]
/packit build

you are approved now! welcome - let us know if you need any help with setting things up

**Comment by jirihnidek** [comment]
@TomasTomecek Thanks. I was wondering what is wrong with my setup.

**Comment by TomasTomecek** [comment]
all green, very nice! :)

**Review by Januson — APPROVED** [review]

**Pull request merged**
